const desaOptions = [
    "Jogotirto",
    "Kalitirto",
    "Sendangtirto",
    "Tegaltirto",
    "Argomulyo",
    "Glagaharjo",
    "Kepuharjo",
    "Wukirsari",
    "Umbulharjo",
    "Caturtunggal",
    "Condongcatur",
    "Maguwoharjo",
    "Ambarketawang",
    "Balecatur",
    "Banyuraden",
    "Nogotirto",
    "Trihanggo",
    "Sidoagung",
    "Sidoarum",
    "Sidokarto",
    "Sidoluhur",
    "Sidomoyo",
    "Sidomulyo",
    "Sidorejo",
    "Purwomartani",
    "Selomartani",
    "Tamanmartani",
    "Tirtomartani",
    "Sendangagung",
    "Sendangarum",
    "Sendangmulyo",
    "Sendangrejo",
    "Sendangsari",
    "Sendangadi",
    "Sinduadi",
    "Sumberadi",
    "Tirtoadi",
    "Tlogoadi",
    "Sumberagung",
    "Sumberarum",
    "Sumberrahayu",
    "Sumbersari",
    "Donoharjo",
    "Minomartani",
    "Sardonoharjo",
    "Sariharjo",
    "Sinduharjo",
    "Sukoharjo",
    "Bimomartani",
    "Sindumartani",
    "Umbulmartani",
    "Wedomartani",
    "Widodomartani",
    "Candibinangun",
    "Hargobinangun",
    "Harjobinangun",
    "Pakembinangun",
    "Purwobinangun",
    "Bokoharjo",
    "Gayamharjo",
    "Madurejo",
    "Sambirejo",
    "Sumberharjo",
    "Wukirharjo",
    "Margoagung",
    "Margodadi",
    "Margokaton",
    "Margomulyo",
    "Caturharjo",
    "Pandowoharjo",
    "Tridadi",
    "Triharjo",
    "Trimulyo",
    "Banyurejo",
    "Lumbungrejo",
    "Margorejo",
    "Merdikorejo",
    "Mororejo",
    "Pondokrejo",
    "Sumberejo",
    "Tambakrejo",
    "Bangunkerto",
    "Donokerto",
    "Girikerto",
    "Wonokerto",
  ];

  const kecamatanOptions = [
    "Berbah",
    "Cangkringan",
    "Depok",
    "Gamping",
    "Godean",
    "Kalasan",
    "Minggir",
    "Mlati",
    "Moyudan",
    "Ngaglik",
    "Ngemplak",
    "Prambanan",
    "Pakem",
    "Seyegan",
    "Sleman",
    "Tempel",
    "Turi",
  ];

  const bangunanOptions = [
    "Barak Evakuasi",
    "Fasilitas Pendidikan",
    "Kantor Pemerintahan",
    "Fasilitas Olahraga",
  ];

export { desaOptions, kecamatanOptions, bangunanOptions };